name: build-pyinstaller
on:
  push:
    branches:
      - stable
      - develop
      - "release/**"
  pull_request:
    branches:
      - stable
      - "release/**"
  workflow_dispatch:

jobs:
  exe:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -e .[full,cloud]
          pip install pypykatz

      - name: Apply pypykatz patch
        run: |
          $patchContent = @'
          From 37be350cf7da5594aa7e10021dc80931281758c8 Mon Sep 17 00:00:00 2001
          From: Odysseas Stavrou <odysseassu@gmail.com>
          Date: Fri, 30 May 2025 00:07:07 +0300
          Subject: [PATCH] Fix Volatility reader

          diff --git a/pypykatz/commons/readers/volatility3/volreader.py b/pypykatz/commons/readers/volatility3/volreader.py
          index 8cdb15f..d8144d6 100644
          --- a/pypykatz/commons/readers/volatility3/volreader.py
          +++ b/pypykatz/commons/readers/volatility3/volreader.py
          @@ -83,21 +83,30 @@ def get_sysinfo(self):
                   return sysinfo

               def find_lsass(self):
          +        if self.framework_version != 1 and self.framework_version != 2:
          +            raise Exception('Unsupported Volatility Framework Version')
          +
                   filter_func = pslist.PsList.create_name_filter(['lsass.exe'])
          +
                   if self.framework_version == 1:
                       layer_name = self.vol_obj.config['primary']
                       symbol_table = self.vol_obj.config['nt_symbols']
          -        elif self.framework_version == 2:
          -            layer_name = self.vol_obj.context.modules[self.vol_obj.config['kernel']].layer_name
          -            symbol_table = self.vol_obj.context.modules[self.vol_obj.config['kernel']].symbol_table_name
          -        else:
          -            raise Exception('Unsupported Volatility Framework Version')
          -        for proc in pslist.PsList.list_processes(
          +
          +            proc_list = pslist.PsList.list_processes(
                           context = self.vol_obj.context,
          -                layer_name = layer_name,
          -                symbol_table = symbol_table,
          -                filter_func = filter_func
          -            ):
          +                layer_name=layer_name,
          +                symbol_table=symbol_table,
          +                filter_func=filter_func
          +            )
          +
          +        elif self.framework_version == 2:
          +            proc_list = pslist.PsList.list_processes(
          +                context=self.vol_obj.context,
          +                kernel_module_name=self.vol_obj.config['kernel'],
          +                filter_func=filter_func
          +            )
          +        
          +        for proc in proc_list:
                       self.lsass_process = proc
                       self.proc_layer_name = self.lsass_process.add_process_layer()
                       self.proc_layer = self.vol_obj.context.layers[self.proc_layer_name]
          '@
          $patchPath = "pypykatz_pr177.patch"
          $patchContent | Out-File -Encoding utf8 $patchPath
          $pypykatzPath = (pip show pypykatz | Select-String "Location:").ToString().Split(": ")[1]
          cd $pypykatzPath
          git apply --ignore-whitespace $env:GITHUB_WORKSPACE\$patchPath
          cd $env:GITHUB_WORKSPACE

      - name: Pyinstall executable
        run: |
          pyinstaller --clean -y vol.spec
          pyinstaller --clean -y volshell.spec

      - name: Move files
        run: |
          mv dist/vol.exe vol.exe
          mv dist/volshell.exe volshell.exe

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: volatility3-pyinstaller
          path: |
            vol.exe
            volshell.exe
            README.md
            LICENSE.txt
